//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblAdmin
{
    public int AdminID { get; set; }
    public string AdminName { get; set; }
    public string AdminEmail { get; set; }
    public string AdminPassword { get; set; }
}

public partial class tblCategory
{
    public tblCategory()
    {
        this.tblProducts = new HashSet<tblProduct>();
    }

    public int CategoryID { get; set; }
    public string CategoryName { get; set; }

    public virtual ICollection<tblProduct> tblProducts { get; set; }
}

public partial class tblCompany
{
    public tblCompany()
    {
        this.tblProducts = new HashSet<tblProduct>();
    }

    public int CompanyID { get; set; }
    public string CompanyName { get; set; }

    public virtual ICollection<tblProduct> tblProducts { get; set; }
}

public partial class tblContact
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Email { get; set; }
    public string Subject { get; set; }
    public string Message { get; set; }
}

public partial class tblCustomerDetail
{
    public tblCustomerDetail()
    {
        this.tblOrderDetails = new HashSet<tblOrderDetail>();
    }

    public int ID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string ShippingAddress { get; set; }
    public string PhoneNo { get; set; }

    public virtual ICollection<tblOrderDetail> tblOrderDetails { get; set; }
}

public partial class tblOrderDetail
{
    public int ID { get; set; }
    public int ProductID { get; set; }
    public decimal ProductPrice { get; set; }
    public int OrderID { get; set; }

    public virtual tblCustomerDetail tblCustomerDetail { get; set; }
}

public partial class tblProduct
{
    public tblProduct()
    {
        this.tblTemps = new HashSet<tblTemp>();
    }

    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public string ProductDescription { get; set; }
    public int CategoryID { get; set; }
    public string ProductImageName { get; set; }
    public string ProductMG { get; set; }
    public int ProductQuantity { get; set; }
    public string ProductUses { get; set; }
    public string ProductIngredients { get; set; }
    public string ProductBenefits { get; set; }
    public string ProductMFG { get; set; }
    public string ProductEXP { get; set; }
    public string ProductFormat { get; set; }
    public string ProductSideEffects { get; set; }
    public string ProductPrecautions { get; set; }
    public Nullable<int> ProductAgeLimit { get; set; }
    public string ProductFormula { get; set; }
    public string ProductManipulations { get; set; }
    public decimal ProductPrice { get; set; }
    public Nullable<int> CompanyID { get; set; }

    public virtual tblCategory tblCategory { get; set; }
    public virtual tblCompany tblCompany { get; set; }
    public virtual ICollection<tblTemp> tblTemps { get; set; }
}

public partial class tblTemp
{
    public int ID { get; set; }
    public int ProID { get; set; }
    public long UniqueNo { get; set; }
    public System.DateTime DateTime { get; set; }

    public virtual tblProduct tblProduct { get; set; }
}

public partial class AllProducts_Result
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public string ProductDescription { get; set; }
    public int CategoryID { get; set; }
    public string ProductImageName { get; set; }
    public string ProductMG { get; set; }
    public int ProductQuantity { get; set; }
    public string ProductUses { get; set; }
    public string ProductIngredients { get; set; }
    public string ProductBenefits { get; set; }
    public string ProductMFG { get; set; }
    public string ProductEXP { get; set; }
    public string ProductFormat { get; set; }
    public string ProductSideEffects { get; set; }
    public string ProductPrecautions { get; set; }
    public Nullable<int> ProductAgeLimit { get; set; }
    public string ProductFormula { get; set; }
    public string ProductManipulations { get; set; }
    public decimal ProductPrice { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public string CategoryName { get; set; }
    public string CompanyName { get; set; }
}

public partial class CartedProducts_Result
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public string ProductDescription { get; set; }
    public int CategoryID { get; set; }
    public string ProductImageName { get; set; }
    public string ProductMG { get; set; }
    public int ProductQuantity { get; set; }
    public string ProductUses { get; set; }
    public string ProductIngredients { get; set; }
    public string ProductBenefits { get; set; }
    public string ProductMFG { get; set; }
    public string ProductEXP { get; set; }
    public string ProductFormat { get; set; }
    public string ProductSideEffects { get; set; }
    public string ProductPrecautions { get; set; }
    public Nullable<int> ProductAgeLimit { get; set; }
    public string ProductFormula { get; set; }
    public string ProductManipulations { get; set; }
    public decimal ProductPrice { get; set; }
    public Nullable<int> CompanyID { get; set; }
    public int ID { get; set; }
    public int ProID { get; set; }
    public long UniqueNo { get; set; }
    public System.DateTime DateTime { get; set; }
}

public partial class DoAdminLogin_Result
{
    public int AdminID { get; set; }
    public string AdminName { get; set; }
    public string AdminEmail { get; set; }
    public string AdminPassword { get; set; }
}

public partial class GetAdmins_Result
{
    public int AdminID { get; set; }
    public string AdminName { get; set; }
    public string AdminEmail { get; set; }
    public string AdminPassword { get; set; }
}

public partial class GetAllCategories_Result
{
    public int CategoryID { get; set; }
    public string CategoryName { get; set; }
}

public partial class GetCategories_Result
{
    public int CategoryID { get; set; }
    public string CategoryName { get; set; }
}

public partial class GetCategoryDepProducts_Result
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public string ProductDescription { get; set; }
    public int CategoryID { get; set; }
    public string ProductImageName { get; set; }
    public string ProductMG { get; set; }
    public int ProductQuantity { get; set; }
    public string ProductUses { get; set; }
    public string ProductIngredients { get; set; }
    public string ProductBenefits { get; set; }
    public string ProductMFG { get; set; }
    public string ProductEXP { get; set; }
    public string ProductFormat { get; set; }
    public string ProductSideEffects { get; set; }
    public string ProductPrecautions { get; set; }
    public Nullable<int> ProductAgeLimit { get; set; }
    public string ProductFormula { get; set; }
    public string ProductManipulations { get; set; }
    public decimal ProductPrice { get; set; }
    public Nullable<int> CompanyID { get; set; }
}

public partial class GetCompanies_Result
{
    public int CompanyID { get; set; }
    public string CompanyName { get; set; }
}

public partial class GetProducts_Result
{
    public int ProductID { get; set; }
    public string ProductName { get; set; }
    public string ProductDescription { get; set; }
    public int CategoryID { get; set; }
    public string ProductImageName { get; set; }
    public string ProductMG { get; set; }
    public int ProductQuantity { get; set; }
    public string ProductUses { get; set; }
    public string ProductIngredients { get; set; }
    public string ProductBenefits { get; set; }
    public string ProductMFG { get; set; }
    public string ProductEXP { get; set; }
    public string ProductFormat { get; set; }
    public string ProductSideEffects { get; set; }
    public string ProductPrecautions { get; set; }
    public Nullable<int> ProductAgeLimit { get; set; }
    public string ProductFormula { get; set; }
    public string ProductManipulations { get; set; }
    public decimal ProductPrice { get; set; }
    public Nullable<int> CompanyID { get; set; }
}
